version: '3.5'

services:
  mmdvmhost:
    build: ./mmdvmhost
    container_name: mmdvmhost
    volumes:
      - ./config/MMDVM.ini:/config/MMDVM.ini
      - ./config/DMRIds.dat:/config/DMRIds.dat:ro
      - ./config/FCSRooms.txt:/config/FCSRooms.txt
      - ./log:/log
    networks:
      mmdvm:
        ipv4_address: 10.10.2.2
    devices:
      - /dev/MMDVM:/dev/MMDVM
    restart: always
    env_file:
     - .env

  dgidgateway:
    build: ./dgidgateway
    container_name: digidgateway
    volumes:
      - ./config/DGIdGateway.ini:/config/DGIdGateway.ini:ro
      - ./config/YSFHosts.txt:/config/YSFHosts.txt:ro
      - ./log:/log
    networks:
      mmdvm:
        ipv4_address: 10.10.2.3
    restart: unless-stopped
    env_file:
     - .env

networks:
  mmdvm:
    ipam:
      driver: default
      config:
        - subnet: 10.10.2.0/24
